// This file is the template used by the setup wizard.
// Do not edit this file directly — edit config.ts instead.
// config.ts is gitignored and will never be pushed to GitHub.

export const config = {
  city: '',
  latitude: 0,
  longitude: 0,
  wsPort: 3001,
  pollInterval: 2000,
  weatherInterval: 10 * 60 * 1000,
  setupComplete: false,

  spotify: {
    enabled: false,
    clientId: '',
    clientSecret: '',
    redirectUri: 'http://127.0.0.1:3001/callback',
  },

  alerts: {
    cpuLoad: 90,
    cpuTemp: 85,
    memPercent: 90,
    gpuLoad: 90,
    gpuTemp: 85,
    diskPercent: 90,
  },

  auth: {
    enabled: false,
    password: '',
    totpSecret: '',
    twoFactorEnabled: false,
  },
};
