import fs from 'fs';
import path from 'path';

const CONFIG_PATH = path.join(process.cwd(), 'src', 'config.ts');

export function configExists(): boolean {
  try {
    if (!fs.existsSync(CONFIG_PATH)) return false;
    const content = fs.readFileSync(CONFIG_PATH, 'utf8');
    return content.includes('setupComplete: true');
  } catch {
    return false;
  }
}

export interface SetupPayload {
  city: string;
  latitude: number;
  longitude: number;
  spotify: {
    enabled: boolean;
    clientId: string;
    clientSecret: string;
  };
  alerts: {
    cpuLoad: number;
    cpuTemp: number;
    memPercent: number;
    gpuLoad: number;
    gpuTemp: number;
    diskPercent: number;
  };
  auth: {
    enabled: boolean;
    password: string;
    totpSecret: string;
    twoFactorEnabled: boolean;
  };
}

export function writeConfig(payload: SetupPayload): void {
  const content = `// Auto-generated by SYS.MONITOR setup wizard
// This file is gitignored — your credentials are safe.
// To re-run setup, delete this file and restart the backend.

export const config = {
  city: ${JSON.stringify(payload.city)},
  latitude: ${payload.latitude},
  longitude: ${payload.longitude},
  wsPort: 3001,
  pollInterval: 2000,
  weatherInterval: ${10 * 60 * 1000},
  setupComplete: true,

  spotify: {
    enabled: ${payload.spotify.enabled},
    clientId: ${JSON.stringify(payload.spotify.clientId)},
    clientSecret: ${JSON.stringify(payload.spotify.clientSecret)},
    redirectUri: 'http://127.0.0.1:3001/callback',
  },

  alerts: {
    cpuLoad: ${payload.alerts.cpuLoad},
    cpuTemp: ${payload.alerts.cpuTemp},
    memPercent: ${payload.alerts.memPercent},
    gpuLoad: ${payload.alerts.gpuLoad},
    gpuTemp: ${payload.alerts.gpuTemp},
    diskPercent: ${payload.alerts.diskPercent},
  },

  auth: {
    enabled: ${payload.auth.enabled},
    password: ${JSON.stringify(payload.auth.password)},
    totpSecret: ${JSON.stringify(payload.auth.totpSecret)},
    twoFactorEnabled: ${payload.auth.twoFactorEnabled},
  },
};
`;
  fs.writeFileSync(CONFIG_PATH, content, 'utf8');
}
